name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        python-version: [ 3.11, 3.12 ]
    name: Tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: Create mocked up files
        run: |
          python app_test_files_creation.py

      - name: Run tests
        run: |
          python -m pytest
  
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.11.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: heroku